### ISSUE TITLE
add MOD to MyriaL

### ISSUE THREAD

**Issue by dhalperi** [uwescience/raco#392]
suggest `a % b` to mean `a mod b`.

Requested by @BrandonHaynes , but obviously needed.

**Comment by dhalperi** [comment]
Note that [it already exists in MyriaX](https://github.com/uwescience/myria/blob/master/src/edu/washington/escience/myria/expression/ExpressionOperator.java#L41), so this should be a simple change that would touch, at least:

* (myrial) scanner.py
* (myrial) parser.py
* expression.py

plus at least one test.

**Comment by senderista** [comment]
I've made the (trivial) code changes for this, but had a question about semantics: do we want to support the rather odd Python 2 semantics for the mod operator with floating point arguments (https://docs.python.org/2/reference/expressions.html)?

The % (modulo) operator yields the remainder from the division of the first argument by the second. The numeric arguments are first converted to a common type. A zero right argument raises the ZeroDivisionError exception. The arguments may be floating point numbers, e.g., 3.14%0.7 equals 0.34 (since 3.14 equals 4*0.7 + 0.34.) The modulo operator always yields a result with the same sign as its second operand (or zero); the absolute value of the result is strictly smaller than the absolute value of the second operand [2].

The integer division and modulo operators are connected by the following identity: x == (x/y)*y + (x%y). Integer division and modulo are also connected with the built-in function divmod(): divmod(x, y) == (x/y, x%y). These identities don’t hold for floating point numbers; there similar identities hold approximately where x/y is replaced by floor(x/y) or floor(x/y) - 1 [3].

**Comment by dhalperi** [comment]
Excellent question.

I'm pretty torn here – usually, Python 3 semantics are pretty good (and [at a glance, they're the same as Python 2](https://docs.python.org/3.3/reference/expressions.html#binary-arithmetic-operations)). But it does seem relatively odd behavior to compute modulo a floating-point.

@BrandonHaynes any preference?

@uwescience/myria ?

**Comment by domoritz** [comment]
Let's not do such silliness unless an actual user requests it.

**Comment by BrandonHaynes** [comment]
My use-case is strictly over the set of integers.  Operating over floats might violate least astonishment, especially given that users may have no idea that Raco operates in Python-land.

**Comment by domoritz** [comment]
In fact, in Myria expressions are executed in Java land. We only look at python for semantics when we think it overs something over Java. For instance integer division is "better" (we think) in python so we mimic its behavior.

**Comment by dhalperi** [comment]
Raco doesn't _semantically_ live in Python-land; we get to pick our own semantics. (Though I often look at Python 3 as a pretty sane model).

* Java does floating point mod
* Python 2 and 3 do floating point mod
* C does not do floating point mod natively, but has `fmod` to do so

I'm still inclined to stick with int-only `mod` because floating point `mod` is just weird.

**Comment by senderista** [comment]
The floating-point semantics was surprising to me as well. I agree that we should stick with the non-overloaded semantics unless we have a reason to do otherwise, especially since there are at least 2 alternatives to choose from: the Python (and Java) semantics, and the IEEE 754 semantics (available in Java from Math.IEEEremainder). So for now I will assume that all arguments to and results from `mod` are integers.

**Comment by senderista** [comment]
Assuming this issue can be closed now?

**Comment by dhalperi** [comment]
Please put text like "fix #392" in your pull request or commit. Then github will auto-close the issue when the PR is merged :)

**Comment by dhalperi** [comment]
[yes, you can manually close now]

**Comment by senderista** [comment]
Thanks, GitHub has come a long way since I last used it professionally!
